#:schema node_modules/wrangler/config-schema.json
name = "rmhong"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "443da71f37424da4a61ce6db58a3c78d" }
]

[assets]
directory = "./public"
